development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_dev
  host: localhost
  pool: 5
  username: sampleapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  host: localhost
  pool: 5
  username: sampleapp
  password: password1
